Gracefully handle `nil` during multi-parameter assignment
When assigning to multi-parameter attributes (like `Date` columns),
Active Record currently handles `""` values as empty values, resulting
in the following:

```ruby
topic = Topic.where.not(last_read: nil).first
topic.attributes = { "last_read(1i)" => "", "last_read(2i)" => "", "last_read(3i)" => "" }
topic.last_read # => nil
```

However, if the `""` values are replaced with `nil`, the assignment
raises a `NoMethodError`:

```
NoMethodError: undefined method 'empty?' for nil
```

In this scenario, `""` and `nil` are semantically equivalent: the value
is absent. However, the implementation invokes [String#empty?][],
which is *not* implemented by [NilClass][].

This commit proposes that the implementation check for [String#blank?][]
instead (which relies on [String#empty?][] under the hood), since there
is also a [NilClass#blank?][] implementation.

[String#empty?]: https://ruby-doc.org/3.4.1/String.html#method-i-empty-3F
[NilClass]: https://edgeapi.rubyonrails.org/classes/NilClass.html
[String#blank?]: https://edgeapi.rubyonrails.org/classes/String.html#method-i-blank-3F
[NilClass#blank?]: https://edgeapi.rubyonrails.org/classes/NilClass.html#method-i-blank-3F